SDK-159 [Java SDK] Increase test coverage up to 99%
incountry/sdk-java pull request #151
Opened 2020-08-27 10:38 UTC by robert-par

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-159](https://incountry.atlassian.net/browse/SDK-159)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2020-08-27 11:39 UTC, VladimirLevitskiy commented
Please increase unit test coverage for **OAuthTokenClient.java**

2020-08-27 11:40 UTC, VladimirLevitskiy requested changes
Please increase unit test coverage for OAuthTokenClient.java

2020-08-28 12:55 UTC, RommeroInCountry requested changes

2020-08-28 12:55 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/http/TokenClientTest.java
> +        assertNotNull(tokenClient.getToken(AUDIENCE_URL, null));
we need to check that tokens are not the same as well

2020-08-28 16:12 UTC, VladimirLevitskiy submitted a review, later dismissed
LGTM

2020-08-28 16:31 UTC, VladimirLevitskiy approved these changes

2020-08-31 10:59 UTC, RommeroInCountry approved these changes
LGTM

2020-08-31 10:59 UTC, merged