DEVOPS-2114: Configure CI for Java SDK
incountry/sdk-java pull request #154
Opened 2020-09-02 17:35 UTC by daniilyar-incountry

2020-09-02 19:37 UTC, VladimirLevitskiy requested changes

2020-09-02 19:37 UTC, VladimirLevitskiy commented on .travis.yml
> +        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git fetch --no-tags https://github.com/${TRAVIS_PULL_REQUEST_SLUG}.git +refs/heads/master:refs/remotes/origin/master; fi
This row is not required

2020-09-02 19:37 UTC, VladimirLevitskiy commented on travis-build.sh
> +gradle integrationTest
Is it possible to make parallel builds for unit tests+ sonar scan and integration tests? For speed up builds

2020-09-03 11:25 UTC, daniilyar-incountry commented on travis-build.sh
> +gradle integrationTest
@VladimirLevitskiy sure, great idea! :) if you are sure that tests support parallel builds and will not deadlock on smth or fight for test resources :)

2020-09-03 14:38 UTC, VladimirLevitskiy approved these changes
LGTM

2020-09-03 15:29 UTC, RommeroInCountry approved these changes
LGTM

2020-09-03 16:37 UTC, RommeroInCountry commented on travis-build.sh
> +  snyk monitor --org=incountry --prune-repeated-subdependencies --remote-repo-url="${APP_NAME}" --project-name="${APP_NAME}:${TRAVIS_BRANCH}"
Does java snyk also use node.js implementation?

2020-09-04 06:45 UTC, samutaa approved these changes

2020-09-04 06:45 UTC, merged