SDK-81 [Java SDK] Add file upload/read methods
incountry/sdk-java pull request #157
Opened 2020-09-14 06:47 UTC by robert-par

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-81](https://incountry.atlassian.net/browse/SDK-81)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2020-09-21 08:40 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +            e.printStackTrace();
change 'printStackTrace()' to using Logger, at this place and in whole project

2020-09-21 10:13 UTC, VladimirLevitskiy requested changes

2020-09-21 10:13 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachmentMeta.java
> +    private String updatedAt;
move this field close to 'createdAt'

2020-09-21 10:13 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachmentMeta.java
> +    private String createdAt;
use Date instead of String for this field and 'updatedAt'

2020-09-21 10:13 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachedFile.java
> +public class AttachedFile {
add method 'toString'

2020-09-21 10:13 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/PopApiResponse.java
> +    private String fileExtension;
Change this field to Map<CustomEnum,String> with name 'metaInfo'

2020-09-21 10:13 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +    public PopApiResponse request(String url, String method, String body, Map<Integer, ApiResponse> codeMap,
Refactor class 'ApiResponse'

2020-09-21 10:13 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +            String fileExtension = null;
This code must be invoked only during file downloading

2020-09-21 10:16 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +        JsonObject json = new JsonObject();
Move JSON transformations to JsonUtils, use string constants for filed names

2020-09-21 10:17 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +        return new Gson().fromJson(response.getContent(), AttachmentMeta.class);
Move JSON transformations to JsonUtils

2020-09-21 10:22 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +        return getAttachmentUrlWithFileId(endPoint, country, recordKey, fileId).concat("/").concat("meta");
1 ) Use string constants. 2) Use constant URI_DELIMETER 3) use method with variable count of parameters for string concatenation

2020-09-21 10:26 UTC, VladimirLevitskiy commented
There is no info about attached files at Record DTO according to 
`When sending GET v2/storage/records/us/{recordKey} POPAPI will return attachment list as a part of record payload `

2020-09-22 10:18 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/dto/AttachedFile.java
> +    private String fileExtension;
We discussed it with Roma, and deeside add it.

2020-09-24 19:10 UTC, VladimirLevitskiy requested changes

2020-09-24 19:10 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/ApiResponse.java
> +public class ApiResponse {
1)It is bad idea to have 2 different classes with same name 'ApiResponse'. Split them or rename. 2) Add to original ApiResponse class expected code statuses to new Storage methods

2020-09-24 19:10 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +    private String getAttachmentUrl(String... urlParts) {
please check that there are no dublications of URI_DELIMETER (//)

2020-09-24 19:10 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/Record.java
> +    public Record setAttachedFiles(List<String> attachedFiles) {
Customer shouldn't use setter for this field. Remove it (or make protected for JSON serializing)

2020-09-25 09:17 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +        if (LOG.isTraceEnabled()) {
If inputStream will be null, we will have NPE.

2020-09-25 10:20 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +    private String getAttachmentUrl(String... urlParts) {
They will be because of "https://"

2020-09-25 12:59 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
> +    private static final String P_MIME_TYPE = "mime_type";
add field  'attachedFiles' to list 'REMOVE_KEYS'

2020-09-25 12:59 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +        if (LOG.isTraceEnabled()) {
use `(inputStream==null)?one:two` there

2020-10-09 10:39 UTC, VladimirLevitskiy requested changes

2020-10-09 10:39 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachmentMeta.java
> +    @SerializedName("created_at")
Please remove this annotation from all DTO classes. Use field name policy configuration during serialization (snake_case)

2020-10-09 14:56 UTC, VladimirLevitskiy requested changes

2020-10-09 15:05 UTC, VladimirLevitskiy requested changes

2020-10-09 15:05 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +import java.nio.file.Path;
Improve test model for file uploading: 1) add 3 files to one record, check 3 files
2) delete one file, check count of files
3) try to read file from unexisting record
4) try to read unexisting file from record
5) tyy to read meta from unexisting file
6) try to update unexisting file by id

2020-10-15 09:26 UTC, VladimirLevitskiy requested changes

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    private static final String FILE_CONTENT = "Hello world!";
Improve test data with dynamic part, e.g. use UUID for random string generation

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    private static final String NEW_FILE_NAME = "new_sdk_incountry_test_file";
use UUID for generation of file name

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    @SuppressWarnings("java:S2696")
remove this SuppressWarnings and fix SonarCube recommendation

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    @Order(201)
change order of this test to 250, to save a distance as a zip for future tests

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    public void addAttachmentTest() throws StorageException, IOException {
Improve this test, add writing byteInputStream without file creation, use custom mime-type

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        Files.delete(tempFile);
add some Assertion to this test

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        assertEquals(1, incomingRecord.getAttachedFiles().size());
add assertion of AttachedFiles' info

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +            String fileName = UUID.randomUUID().toString();
Use byteUnputStream instead of creating files at low-speed file system

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                LOG.error("Exception during attached files reading", exception);
save exception and add assertNull (savedException) after catch block

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    @Order(302)
change order of all folowing tests to 350+

2020-10-15 09:26 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        assertTrue(ex.getMessage().contains("Code=404"));
It is possible to use more text at this check?

2020-10-15 13:31 UTC, VladimirLevitskiy requested changes

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +        response.setContent(jsonObject.get(ATTACHED_FILE_ID).getAsString());
return expected data instead of setting 'Content' in 'response'

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/RequestParameters.java
> +    public RequestParameters(String method, Map<Integer, ApiResponseCodes> codeMap, String contentType) {
use another constructor there

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/RequestParameters.java
> +    public String toString() {
not all params are there

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/ApiResponse.java
> +    public String toString() {
not all params are there

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +        JsonObject jsonObject = (JsonObject) JsonUtils.getDataFromJson(response.getContent(), JsonObject.class);
This class should not contain direct low-level JSON transformations. Move them to another class

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/RequestParameters.java
> +    private String contentType;
May be set it appl/json by default? is there another values?

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +    private static final String MSG_ERR_NOT_AVAILABLE_FILE_INPUT_STREAM = "File input stream is not available";
without 'FIle', it can be ByteInputStream

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +        checkParameters(country, recordKey);
move it upper then checking file

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +            LOG.trace("deleteAttachment results={}", true);
use simple string, without formatting

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachedFile.java
> +                ", fileName=" + fileName +
Name is PII? If 'yes' - hash it at this method

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachmentMeta.java
> +                "createdAt=" + createdAt +
hash PII data there

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +    private void checkParameters(String url, RequestParameters requestParameters) throws StorageClientException {
create class like NullChecker with method checkNull(Logger, objectToCHeck, StorageExceptionWithMessage)

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +            Pattern pattern = Pattern.compile(".*filename\\*=UTF-8\\'\\'(.*)");
Why we do so low-level transformations?

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/ApiResponse.java
> +package com.incountry.residence.sdk.tools.models;
change package name from 'models' to another, e.g. containers

2020-10-15 13:31 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
> +        public String translateName(Field field) {
Is there automatic conversation between snake_case and camelCase?

2020-10-15 13:31 UTC, VladimirLevitskiy commented on build.gradle
> +    compile group: 'commons-io', name: 'commons-io', version: '2.7'
move dependency version to property file like others

2020-10-15 18:16 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +        JsonObject jsonObject = (JsonObject) JsonUtils.getDataFromJson(response.getContent(), JsonObject.class);
It is simple conversion json string to object using JsonUtils.getData FromJson method. Only difference that in this case I'm using JsonObject instead some self writing class.

2020-10-15 18:24 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/models/RequestParameters.java
> +    private String contentType;
yes

2020-10-15 18:36 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/dto/AttachedFile.java
> +                ", fileName=" + fileName +
I guess no. But I will clarify this question.

2020-10-15 18:38 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/dto/AttachmentMeta.java
> +                "createdAt=" + createdAt +
What concrete field you mean?

2020-10-15 19:05 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +            Pattern pattern = Pattern.compile(".*filename\\*=UTF-8\\'\\'(.*)");
We have "content-disposition" header with "attachment; filename*=UTF-8'’filename.txt" content. And I get file name from it by using regular expressions

2020-10-15 19:10 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
> +        public String translateName(Field field) {
The problem is that we have not only snake_case names but also "filename", that we must convert to "fileName"

2020-10-15 19:17 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +    private void checkParameters(String url, RequestParameters requestParameters) throws StorageClientException {
It is good idea, but it include refactoring all over the project, and I think it have sense to be done in separate task

2020-10-16 14:51 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    @SuppressWarnings("java:S2696")
it require to stop using "fileId" field because it is static. but I need it for sharing file id with other tests.

2020-10-16 14:54 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    public void addAttachmentTest() throws StorageException, IOException {
the test purpose to show how can be upload a real file

2020-10-16 15:08 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    private static final String FILE_CONTENT = "Hello world!";
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 15:08 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    private static final String NEW_FILE_NAME = "new_sdk_incountry_test_file";
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 15:08 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    @Order(201)
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 15:08 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        Files.delete(tempFile);
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 15:09 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        assertEquals(1, incomingRecord.getAttachedFiles().size());
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 15:09 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +            String fileName = UUID.randomUUID().toString();
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 15:09 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                LOG.error("Exception during attached files reading", exception);
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 15:09 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    @Order(302)
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 15:09 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        assertTrue(ex.getMessage().contains("Code=404"));
https://incountry.atlassian.net/browse/SDK-241

2020-10-16 16:10 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/Storage.java
> +    String addAttachment(String country, String recordKey, InputStream fileInputStream, String fileName, boolean upsert) throws StorageClientException, StorageServerException;
Please add optional mimetype param as well to be passed along with filedata to POPAPI.

2020-10-16 16:14 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/Storage.java
> +     * @param upsert http method flag, if true used PUT method otherwise POST
upsert - if true will overwrite existing file with the same name. Otherwise will throw exception

2020-10-16 16:32 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +        JsonObject jsonObject = (JsonObject) JsonUtils.getDataFromJson(response.getContent(), JsonObject.class);
move all this transformation to JsonUtils. HttpDao must not have direct JSON transformations

2020-10-16 16:38 UTC, VladimirLevitskiy requested changes

2020-10-16 16:38 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/Record.java
> +    public Record setAttachedFiles(List<AttachmentMeta> attachedFiles) {
remove this setter, it is prohibited for customers

2020-10-16 16:41 UTC, VladimirLevitskiy requested changes

2020-10-16 16:41 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/Record.java
> +    @SerializedName("attachments")
Remove this annotation. Rename field or use external mapping

2020-10-16 16:45 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    @SuppressWarnings("java:S2696")
make this variable simple unstatic field of this class, fill it and use it (like fields 'storage','secretKeyAccessor', etc)

2020-10-16 16:50 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/ApiResponse.java
> +        this.content = content;
I meant to use the one full constuctor at implementation of another constructor

2020-10-16 16:51 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/RequestParameters.java
> +    public RequestParameters(String method, Map<Integer, ApiResponseCodes> codeMap, String contentType) {
the same, I meant to use the one full constructor at implementation of another constructor

2020-10-16 16:55 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/models/RequestParameters.java
> +    private String contentType;
Please add another constructor without parameter 'contentType', use default value 'application/json' at this constructor, use another full constructor at implementation of this one

2020-10-16 16:57 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachmentMeta.java
> +                "createdAt=" + createdAt +
what of these fields can be PII?
```
private String downloadLink;
private String fileId;
private String fileName;
private String mimeType;
```

2020-10-16 16:59 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +    private void checkParameters(String url, RequestParameters requestParameters) throws StorageClientException {
Please create this class and use it only there. Other same refactoring will be at other tasks

2020-10-16 17:02 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
> +        public String translateName(Field field) {
'filename' is a correct word. Use it. And use auto name transformations instead of manual mapping

2020-10-16 17:04 UTC, VladimirLevitskiy requested changes
Please fix all the recommendations

2020-10-16 17:14 UTC, RommeroInCountry requested changes

2020-10-16 17:14 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +            metaInfo.put(MetaInfoTypes.NAME, fileName);
I don't see any uri transformations for utf-8 symbols here

2020-10-16 17:14 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +        }
Why we don't specify content_type for file upload?

2020-10-16 17:14 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +    private boolean canRetry(ApiResponseCodes params, int retryCount) {
why we need this method anyways? If it does help - we don't need to pass ApiResponseCodes params just for the sake to call only params.isCanRetry() here. Just send the bool

2020-10-19 18:34 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/dto/AttachedFile.java
> +        this.fileExtension = fileExtension;
As I know there isn't special recommendations about this case. I added fileName field witch contains file name with extension and fileExtension field with only file extension because I thought it will be more suitable for customers.

2020-10-20 08:57 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +            metaInfo.put(MetaInfoTypes.NAME, fileName);
I'm not pushed corrections yet

2020-10-20 09:04 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +        }
Because http-client method that attach file to request, required to pass content type to it

2020-10-21 10:04 UTC, VladimirLevitskiy requested changes
Please develop requested changes and improve unit tests code coverage, it is possible to reach about 99%

2020-10-21 13:08 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/dto/AttachmentMeta.java
> +    private Date createdAt;
it will require initializing this field which is not provided by logic.

2020-10-21 13:34 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/HttpAgentImpl.java
> +            Pattern pattern = Pattern.compile(".*filename\\*=UTF-8\\'\\'(.*)");
here what we get from popapi "filename*=UTF-8''file.txt"

2020-10-22 08:18 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachedFile.java
> +    private InputStream fileContent;
Make 'final' ALL these fields (fileContent,fileName,fileExtension), not only one field

2020-10-22 10:40 UTC, VladimirLevitskiy submitted a review, later dismissed
LGTM

2020-10-22 10:56 UTC, VladimirLevitskiy approved these changes

2020-10-22 12:33 UTC, RommeroInCountry requested changes

2020-10-22 12:36 UTC, RommeroInCountry requested changes

2020-10-22 12:36 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/dto/AttachedFile.java
> +        this.fileExtension = fileExtension;
please remove fileExtenstion. Let's just have fileName which already contains extenstion. Let's not overengineer things

2020-10-22 13:28 UTC, RommeroInCountry requested changes

2020-10-22 13:28 UTC, RommeroInCountry commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        fileId = attachmentMeta.getFileId();
please add simple assertion that filename is exactly the same in this very PR

2020-10-22 13:47 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
> +    public static <T> Object getDataFromJson(String string, Class<T> clazz) throws StorageClientException {
it is normal for java when you work with "Class" type)

2020-10-22 13:57 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/Storage.java
> +     * @return AttachmentMeta object which contains id of attached file
In this case there will be only fileId field that's why I wrote only about it.
But I will use this description for getAttachmentMeta method, to make it more clear.

2020-10-22 14:47 UTC, RommeroInCountry requested changes

2020-10-22 14:47 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/Storage.java
> +     * @return AttachmentMeta object which contains id of attached file
Why only fileId? PoPAPI returns full meta for this request

2020-10-23 11:17 UTC, RommeroInCountry requested changes

2020-10-23 11:17 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/Storage.java
> +     * @return AttachmentMeta object which contains fileId, mimeType, size, filename, downloadLink, updatedAt and createdAt
Let it be - "attachment meta information: fileId, mimeType, size, etc."

2020-10-23 14:49 UTC, RommeroInCountry approved these changes
LGTM

2020-10-23 15:37 UTC, VladimirLevitskiy requested changes

2020-10-23 15:37 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/dto/AttachedFile.java
> +    public AttachedFile(InputStream fileContent, String fileName) {
Do we need to validate filename? (e.g. !_/1233234@#$%^&*)

2020-10-23 16:01 UTC, VladimirLevitskiy approved these changes
LGTM

2020-10-23 16:03 UTC, merged