SDK-241 [Java SDK] Improve integration tests
incountry/sdk-java pull request #160
Opened 2020-10-27 08:31 UTC by robert-par

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-241](https://incountry.atlassian.net/browse/SDK-241)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2020-10-27 14:06 UTC, RommeroInCountry submitted a review, later dismissed
LGTM

2020-10-27 14:19 UTC, VladimirLevitskiy requested changes

2020-10-27 14:19 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
>      private static final String NEW_FILE_NAME = "new_sdk_incountry_test_file";
Use UUID for NEW_FILE_NAME too

2020-10-27 14:19 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
>      @SuppressWarnings("java:S2696")
remove this SuppressWarnings and fix it's requirments

2020-10-27 14:19 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
>          assertTrue(ex.getMessage().contains("Code=404"));
It is possible to use more text at this check?

2020-10-27 14:19 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    @SuppressWarnings("java:S2696")
remove this SuppressWarnings too

2020-10-27 16:26 UTC, VladimirLevitskiy approved these changes
LGTM

2020-10-28 12:52 UTC, RommeroInCountry approved these changes
LGMT

2020-10-28 13:31 UTC, merged