SDK-236 [Java SDK] Add non hashing mode for key1-key10
incountry/sdk-java pull request #161
Opened 2020-10-30 15:31 UTC by robert-par

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-236](https://incountry.atlassian.net/browse/SDK-236)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2020-11-03 09:25 UTC, VladimirLevitskiy requested changes

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/crypto/CryptoManager.java
> +    public String createSearchKeyHash(String key) {
Please merge 3 trivial methods into 1: createSearchKeyHash, createKeyHash and createHash

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
> +    private static final List<String> SEARCH_KEYS = Arrays.asList(P_KEY_1, P_KEY_2, P_KEY_3, P_KEY_4, P_KEY_5, P_KEY_6,
Is profileKey unsupported? And what about serviceKey1,2 ?

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageConfig.java
> +    private boolean hashSearchKeys = true;
Add it to methods: copy, toString

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
>                  checkParameters(country, record.getRecordKey());
rename 'checkParameters' to 'checkCountryAndRecordKey'

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +                checkRecordsKeys(record);
rename to 'checkRecordSearchKeys'

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/crypto/CryptoManagerTest.java
> +    @MethodSource("getEncryptedString")
Move this test closer to 'getEncryptedString' or vice versa

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/crypto/CryptoManagerTest.java
> +        CryptoManager manager = new CryptoManager(null, "ENV_ID", null, false, true);
please use constant field for string literal 'ENV_ID' (ignore case)

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/crypto/CryptoManager.java
> +    private boolean hashSearchKeys;
make fields 'hashSearchKeys' and 'normalizeKeys' final

2020-11-03 09:25 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/crypto/CryptoManager.java
> +    public CryptoManager(SecretKeyAccessor keyAccessor, String envId, List<Crypto> customEncryptionList, boolean normalizeKeys, boolean hashSearchKeys)
There is no one test (unit and integration), where hashSearchKeys=false. Please, create some ones

2020-11-03 10:19 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                .keyEq(StringField.KEY2, KEY_2)
Ok, I understand your idea, about making separate test for new code, it makes sense. Regarding rollbacking original test, I changed it because it was wrong, key1...key10 are case sensitive

2020-11-03 10:20 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                .keyEq(StringField.KEY2, KEY_2)
The same like at my previous answer

2020-11-04 15:57 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/tools/crypto/CryptoManager.java
> +    public CryptoManager(SecretKeyAccessor keyAccessor, String envId, List<Crypto> customEncryptionList, boolean normalizeKeys, boolean hashSearchKeys)
There is "testCreateSearchKeyHash()" test in CryptoManagerTest class which is tasting the case when hashSearchKeys=false

2020-11-09 17:02 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        storageWithEncryption = StorageImpl.getInstance(loadFromEnv(INT_INC_ENVIRONMENT_ID),
please rename it to 'storageWithApiKey' and use constructor with StorageConfig

2020-11-09 17:04 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        storageWithUnheshSearchKeys = StorageImpl.getInstance(config);
typo, change to 'storageWithUnhashedKeys'

2020-11-09 17:06 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        storageForAttachment = StorageImpl.getInstance(loadFromEnv(INT_INC_ENVIRONMENT_ID),
Do not use additional storage for atachements (especially with deprecated ApiKey). Run tests for work with files with all other storage instances

2020-11-09 17:08 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +    public void initializeStorages() throws StorageException {
please add one storage instance without encryption.

2020-11-09 17:15 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                Arguments.of(storageWithEncryption, RECORD_KEY_WITH_ENCRYPTION, BATCH_RECORD_KEY_WITH_ENCRYPTION),
I think this list must contains:
1) storage without encryption (API key)
2) storage with secret as key (isKey=true) (OAuth)
3) storage with secret as password (isKey=false) (OAuth)
4) storage with custom encryption (see Fernet Crypto)
5) storage with normalizeKey=true
6) storage with unhashed search keys

Most of existing tests (createRecord, batchWrite, read, find, delete, all attachement manipulations) must work with this list of storages. Very special tests (like 'readIgnoreCaseTest') can be non-parametrized and work only with one special storage instance

2020-11-09 17:25 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
> +    private static List<String> hashValue(FilterStringParam param, String paramsName, CryptoManager cryptoManager) {
rename 2nd argument to 'paramName' or 'parameterName'

2020-11-09 17:27 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
> +        List<String> values = (cryptoManager != null ? hashValue(param, paramName, cryptoManager) : param.getValues());
I think we have no case, when cryptoManager==null. We can get rid of this check (at this class totally)

2020-11-09 17:28 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageConfig.java
> +    public StorageConfig setHashSearchKeys(boolean hashSearchKeys) {
Please add JavaDoc

2020-11-10 14:05 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        storageForAttachment = StorageImpl.getInstance(loadFromEnv(INT_INC_ENVIRONMENT_ID),
I can't do it because in this case I need to share file id with different tests

2020-11-13 14:08 UTC, VladimirLevitskiy approved these changes

2020-11-17 12:35 UTC, RommeroInCountry requested changes

2020-11-17 12:35 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +    private void checkKey(String key) throws StorageClientException {
this check should only occur if hashSearchKeys is disabled

2020-11-17 12:35 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/crypto/CryptoManager.java
> +        return org.apache.commons.codec.digest.DigestUtils.sha256Hex(normalizeKeys ? stringToHash.toLowerCase() : stringToHash);
can it be imported in file import section?

2020-11-17 12:35 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +        assertTrue(jsonString.contains("\"profile_key\":{\"$not\":[\"" + "08f377ef929c1c98ff7bfa25410979640c6fcbb0f651f1834bd2db2688273473" + "\"]}"));
why hardcoded sha hashes here?

2020-11-17 12:35 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterBuilderIsolatedTest.java
>          //{"filter":{"record_key":["7dd05cb65e032bb0c4de5663b0d55a42dea08414018a6c4fe4475f968bd78137","92615295d3285663166fab9e7a9371035448579643d1fcd12c48572c39c3e455"],"key1":["81bc20701d75abe5e2b0
please remove commented out code

2020-11-17 12:35 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
> +        return new CryptoManager(encrypt ? secretKeyAccessor : null, "envId", null, false, true);
We need unit tests for hashSearchKeys = false to test that keys are correctly kept unhashed

2020-11-18 07:51 UTC, robert-par commented on src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
> +        return new CryptoManager(encrypt ? secretKeyAccessor : null, "envId", null, false, true);
We have this kind of test in CryptoManagerTest called testCreateSearchKeyHash.

2020-11-18 07:55 UTC, robert-par commented on src/test/java/com/incountry/residence/sdk/search/FindFilterBuilderIsolatedTest.java
>          //{"filter":{"record_key":["7dd05cb65e032bb0c4de5663b0d55a42dea08414018a6c4fe4475f968bd78137","92615295d3285663166fab9e7a9371035448579643d1fcd12c48572c39c3e455"],"key1":["81bc20701d75abe5e2b0
It added to make clear what we search in json.

2020-11-18 11:11 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterBuilderIsolatedTest.java
>          //{"filter":{"record_key":["7dd05cb65e032bb0c4de5663b0d55a42dea08414018a6c4fe4475f968bd78137","92615295d3285663166fab9e7a9371035448579643d1fcd12c48572c39c3e455"],"key1":["81bc20701d75abe5e2b0
please remove, it's redundant

2020-11-18 11:25 UTC, RommeroInCountry requested changes

2020-11-18 11:25 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/HttpDaoImplTests.java
> +        return new CryptoManager(encrypt ? secretKeyAccessor : null, "envId", null, false, true);
Key should not be hashed when false. 
The test you mentioned asserts
`assertEquals(crypto.createKeyHash(someKey), crypto.createSearchKeyHash(someKey.toLowerCase()));`
(btw, why the lowercase? if it's normalize key - it should be tested both with and without and it should be clear from the test code itself when normalize is on and off - not just true/false values in constructor - please use variables with meaningful names)

^ Lefthand value in the assertion above is always a hash. If the righthand is a hash too, then the implementation is wrong.

You should test smth like
```
CryptoManager crypto = new CryptoManager(....hashSearchKeys=false);
...
`assertEquals(someKey, crypto.createSearchKeyHash(someKey));`
```

2020-11-18 12:08 UTC, RommeroInCountry requested changes

2020-11-18 12:08 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/crypto/CryptoManager.java
> +        }
what is this for?

2020-11-18 12:08 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +//        assertTrue(jsonString.contains("\"profile_key\":{\"$not\":[\"" + "08f377ef929c1c98ff7bfa25410979640c6fcbb0f651f1834bd2db2688273473" + "\"]}"));
please remove commented out code

2020-11-18 13:24 UTC, RommeroInCountry approved these changes
LGTM

2020-11-18 14:18 UTC, RommeroInCountry submitted a review, later dismissed
LGTM

2020-11-18 17:07 UTC, VladimirLevitskiy approved these changes

2020-11-18 17:09 UTC, RommeroInCountry approved these changes

2020-11-19 08:51 UTC, merged