SDK-237 [Java SDK] Add search_keys filter support
incountry/sdk-java pull request #163
Opened 2020-11-13 09:39 UTC by robert-par

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-237](https://incountry.atlassian.net/browse/SDK-237)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2020-11-19 15:53 UTC, RommeroInCountry requested changes

2020-11-19 15:53 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +    }
Can we please do this validation simply when constructing builder?

2020-11-19 15:53 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +            assertEquals("Existence key1-key10 and search_keys at the same time is not acceptable", ex.getMessage());
search_keys cannot be used in conjunction with regular key1...key10 lookup - this error message would be better

2020-11-20 10:40 UTC, robert-par commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +    }
What constructer you mean, StorageInpl?

2020-11-20 10:57 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +    }
FindFilterBuilder one

2020-11-20 11:09 UTC, RommeroInCountry approved these changes
LGTM

2020-11-23 14:54 UTC, VladimirLevitskiy requested changes

2020-11-23 14:54 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                .keyEq(StringField.SEARCH_KEYS, KEY_1);
It is better to search part of a key there, e.g. if key1="John Smith" you will need to find 'John%'

2020-11-23 14:54 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +    private static final String MSG_ERR_KEY1_KEY10_AND_SEARCH_KEYS = "search_keys cannot be used in conjunction with regular key1...key10 lookup";
The naming of fields at Java SDK is different from other SDK. Please rename variable names in this message

2020-11-23 14:54 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +    }
I think it is a good possibility to transfer search criteria validation logic to FindFilterBuilder

2020-11-25 15:36 UTC, RommeroInCountry approved these changes
LGTM

2020-11-26 09:47 UTC, VladimirLevitskiy requested changes

2020-11-26 09:47 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                .setApiKey(loadFromEnv(INT_INC_API_KEY))
Please use ClientID+ClientSecret instead of ApiKey there

2020-11-26 09:47 UTC, VladimirLevitskiy commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                .setHashSearchKeys(false);
Please add encryption by passing a secret key accessor

2020-11-26 13:29 UTC, robert-par commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +                .setHashSearchKeys(false);
task says "searchKeys parameter should not be hashed/encrypted and should not be normalized using the option normalizeKeys"

2020-11-26 16:45 UTC, RommeroInCountry submitted a review, later dismissed
LGTM

2020-11-27 21:20 UTC, VladimirLevitskiy approved these changes

2020-11-27 21:20 UTC, VladimirLevitskiy commented
LGTM

2020-11-30 11:06 UTC, RommeroInCountry approved these changes
LGTM

2020-11-30 13:05 UTC, merged