SDK-268 [Java SDK] File storage README
incountry/sdk-java pull request #165
Opened 2020-11-27 09:29 UTC by robert-par

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-268](https://incountry.atlassian.net/browse/SDK-268)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-01-11 08:09 UTC, VladimirLevitskiy requested changes
Please actualize it after merging PR https://github.com/incountry/sdk-java/pull/173

2021-01-20 15:01 UTC, RommeroInCountry requested changes

2021-01-20 15:01 UTC, RommeroInCountry commented on README.md
> +     * @param fileName  file name which is not mandatory (can be null) if mimeType passed
fileName file name (optional if mimeType provided)
mimeType file MIME type (optional if fileName provided)

2021-01-21 12:48 UTC, VladimirLevitskiy approved these changes

2021-01-21 15:30 UTC, merged