SDK-271 [Java SDK] Update README introduction section
incountry/sdk-java pull request #167
Opened 2020-12-01 08:54 UTC by robert-par

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-271](https://incountry.atlassian.net/browse/SDK-271)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-01-11 08:06 UTC, VladimirLevitskiy approved these changes

2021-01-20 15:19 UTC, RommeroInCountry requested changes

2021-01-20 15:19 UTC, RommeroInCountry commented on README.md
> +To access your data in InCountry Platform by using Java SDK, you need to create an instance of the Storage class using the getInstance method and pass StorageConfig object to it. You can retrieve the
Please highlight getInstance, StorageConfig

2021-01-20 15:19 UTC, RommeroInCountry commented on README.md
> +storageOrdinary = StorageImpl.getInstance(config);
missing default secret passed to SDK. Please use the simplest one - secret from string

2021-01-20 15:19 UTC, RommeroInCountry commented on README.md
> +Below you can find a full list of possible configuration options for creating a Storage instance.
that's not the full list below. Please provide an extensive javadoc here

2021-01-20 15:19 UTC, RommeroInCountry commented on README.md
>  You can turn off encryption (not recommended) by providing `null` value for parameter `secretKeyAccessor`.
please remove this line completely (see https://github.com/incountry/sdk-nodejs#storage-configuration)

2021-01-20 15:19 UTC, RommeroInCountry commented on README.md
> +Below you can find API Key authorization usage example:
this example should be inside of a warning section

2021-01-20 17:28 UTC, VladimirLevitskiy submitted a review, later dismissed

2021-01-20 18:05 UTC, VladimirLevitskiy approved these changes

2021-01-20 18:21 UTC, VladimirLevitskiy submitted a review, later dismissed

2021-01-20 19:00 UTC, VladimirLevitskiy approved these changes

2021-01-20 19:16 UTC, closed without merging

2021-01-20 19:16 UTC, VladimirLevitskiy commented
New PR will be created instead of force push