SDK-288
incountry/sdk-java pull request #176
Opened 2021-01-13 12:54 UTC by VladimirLevitskiy

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-288](https://incountry.atlassian.net/browse/SDK-288)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-01-19 09:29 UTC, robert-par submitted a review, later dismissed

2021-01-20 16:06 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
>      private static final List<String> REMOVE_KEYS = Arrays.asList(P_BODY, P_PRECOMMIT_BODY, P_CREATED_AT, P_UPDATED_AT,
Let's think of a solution to get rid of this approach in future. It's kinda strange-looking :)

2021-01-20 16:36 UTC, RommeroInCountry requested changes
Please mention new keys in Readme in **List of available record fields** section

2021-01-21 12:51 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/JsonUtils.java
>      private static final List<String> REMOVE_KEYS = Arrays.asList(P_BODY, P_PRECOMMIT_BODY, P_CREATED_AT, P_UPDATED_AT,
It will be done during task https://incountry.atlassian.net/browse/SDK-291

2021-01-29 13:20 UTC, RommeroInCountry approved these changes
LGTM

2021-01-29 13:26 UTC, robert-par approved these changes

2021-01-29 13:45 UTC, merged