SDK-296
incountry/sdk-java pull request #177
Opened 2021-01-19 18:52 UTC by VladimirLevitskiy

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-296](https://incountry.atlassian.net/browse/SDK-296)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-01-29 14:24 UTC, RommeroInCountry requested changes

2021-01-29 14:24 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/dto/search/FindFilterBuilder.java
> +    public FindFilterBuilder nullable(StringField field, boolean isNull) {
I'd split into keyIsNull, keyIsNotNull to keep builder consistent

2021-01-29 14:39 UTC, RommeroInCountry approved these changes
LGTM

2021-02-08 10:23 UTC, robert-par approved these changes

2021-02-08 10:24 UTC, merged