SDK-379 [Java SDK] Introduce throttling to http requests
incountry/sdk-java pull request #224
Opened 2021-05-27 15:26 UTC by VladimirLevitskiy

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-379](https://incountry.atlassian.net/browse/SDK-379)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-06-29 16:26 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/ThrottlingRequestExecutor.java
> +    private static final String USER_AGENT_VALUE = "SDK-Java/" + Version.BUILD_VERSION;
it's kinda wrong to do headers in this class. I'd leave them be as they are now. Or even moving them further higher in stack. These are just custom headers for the request that should be simply moved further down the pipe. Let's discuss it on the DSU call

2021-06-29 16:26 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/ThrottlingRequestExecutor.java
> +    private static final String USER_AGENT_VALUE = "SDK-Java/" + Version.BUILD_VERSION;
p.s. USER_AGENT -> USER_AGENT_HEADER_NAME, USER_AGENT_VALUE -> USER_AGENT_HEADER_VALUE

2021-06-29 16:28 UTC, RommeroInCountry requested changes
Let's have a call on the proposed changes

2021-06-30 11:26 UTC, VladimirLevitskiy commented
> Let's have a call on the proposed changes

done

2021-07-02 12:21 UTC, RommeroInCountry approved these changes

2021-07-05 13:38 UTC, robert-par approved these changes

2021-07-06 09:45 UTC, merged