SDK-312
incountry/sdk-java pull request #225
Opened 2021-06-01 15:11 UTC by VladimirLevitskiy

Pull Request Checklist
======================

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture+Draft

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-312](https://incountry.atlassian.net/browse/SDK-312)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-07-07 14:00 UTC, RommeroInCountry requested changes

2021-07-07 14:00 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +        Record recorderRecord = transformer.getRecord(recordedTransferRecord);
please see C# note on the naming

2021-07-07 15:29 UTC, RommeroInCountry submitted a review, later dismissed

2021-07-08 10:55 UTC, artemgolozubov approved these changes
LGTM

2021-07-08 10:55 UTC, artemgolozubov commented on README.md
> +By default, data at a find result is not sorted. To sort the returned records by one or multiple keys use method `sortBy` of `FindFilter` .
```suggestion
By default, data at a find result is not sorted. To sort the returned records by one or multiple keys use method `sortBy` of `FindFilter`.
```

2021-07-08 11:06 UTC, artemgolozubov approved these changes
LGTM

2021-07-08 14:15 UTC, RommeroInCountry approved these changes

2021-07-08 14:38 UTC, merged