SDK-393 [Java SDK] Bulk delete
incountry/sdk-java pull request #227
Opened 2021-07-20 15:20 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-393](https://incountry.atlassian.net/browse/SDK-393)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-08-16 13:37 UTC, RommeroInCountry requested changes

2021-08-16 13:37 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/Storage.java
> +
please don't forget to update this text as well according to comments in README

2021-08-23 11:29 UTC, RommeroInCountry approved these changes

2021-08-23 12:28 UTC, robert-par approved these changes

2021-08-23 13:11 UTC, merged