SDK-407 [Java SDK] Comparing operators to date field filtering created_at and updated_at are not working
incountry/sdk-java pull request #228
Opened 2021-07-26 13:44 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-407](https://incountry.atlassian.net/browse/SDK-407)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-07-27 11:25 UTC, robert-par commented on README.md
> +    private DateZonedDateTime updatedAt;
This is typo, please change to ZonedDateTime.

2021-07-27 13:47 UTC, robert-par submitted a review, later dismissed

2021-07-30 12:14 UTC, RommeroInCountry requested changes

2021-07-30 12:14 UTC, RommeroInCountry commented on README.md
> +Field `expiresAt` can be set by user. All date field values are stored and returned in UTC+0 timezone accurate to microseconds.
in UTC+0 with microseconds precision

2021-07-30 12:51 UTC, RommeroInCountry approved these changes

2021-07-30 12:53 UTC, RommeroInCountry requested changes

2021-07-30 12:53 UTC, RommeroInCountry commented on src/integration/java/com/incountry/residence/sdk/StorageIntegrationTest.java
> +        assertTrue(readRecord.getCreatedAt().isEqual(findResult.getRecords().get(0).getCreatedAt()));
I'd double check that the received record is also the one we read initially. Just in case. Comparing only dates is not a 100% verification of equality of records :)

2021-07-30 13:04 UTC, RommeroInCountry approved these changes

2021-08-04 11:00 UTC, robert-par approved these changes

2021-08-04 11:21 UTC, merged