SDK-440 - Update of readme.md
incountry/sdk-java pull request #241
Opened 2021-09-08 05:27 UTC by vadim-rutkevich-incountry

Work relates to SDK-440 - Update of readme.md

2021-09-08 13:45 UTC, VladimirLevitskiy approved these changes

2021-09-08 15:47 UTC, RommeroInCountry requested changes

2021-09-08 15:47 UTC, RommeroInCountry commented on README.md
> +You can use the `batchDelete` method in order to delete multiple records from the InCountry platform. As of now, the SDK supports the deletion of records only by providong a list of the `RecordKey` v
providong - typo

2021-09-08 16:13 UTC, RommeroInCountry requested changes

2021-09-08 16:13 UTC, RommeroInCountry commented on README.md
> +You can set the `isForCustomEncryption` parameter in the JSON format within the `SecretsData` method , as follows:
You can also specify a key for custom encryption by setting the `isForCustomEncryption` parameter in `SecretsData` JSON representation:

2021-09-08 16:15 UTC, RommeroInCountry commented on README.md
> +You can use the `batchDelete` method in order to delete multiple records from the InCountry platform. As of now, the SDK supports the deletion of records only by providong a list of the `RecordKey` v
as of now -> for now

2021-09-09 07:48 UTC, vadim-rutkevich-incountry commented on README.md
> +You can set the `isForCustomEncryption` parameter in the JSON format within the `SecretsData` method , as follows:
updated

2021-09-09 13:19 UTC, RommeroInCountry approved these changes

2021-09-13 11:05 UTC, VladimirLevitskiy approved these changes

2021-09-13 11:05 UTC, merged