SDK-456 [Java SDK] Add support for enhanced search
incountry/sdk-java pull request #250
Opened 2021-10-14 13:12 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-456](https://incountry.atlassian.net/browse/SDK-456)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-11-02 10:53 UTC, RommeroInCountry requested changes

2021-11-02 10:53 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/EncryptedDtoTransformerTest.java
> +                .keyEq(StringKeyField.KEY1, "Key1 Value")
Please make a note somewhere that we'll need this to be mentioned in "release notes" as a "migrating to 5.0.0" example. I believe this is a breaking change, right?

2021-11-02 13:24 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/EncryptedDtoTransformerTest.java
> +                .keyEq(StringKeyField.KEY1, "Key1 Value")
Yes

2021-11-02 14:19 UTC, RommeroInCountry approved these changes

2021-11-03 06:16 UTC, robert-par approved these changes

2021-11-03 07:03 UTC, merged