SDK-459
incountry/sdk-java pull request #253
Opened 2021-11-01 19:32 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-459](https://incountry.atlassian.net/browse/SDK-459)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-11-09 12:10 UTC, RommeroInCountry requested changes

2021-11-09 12:23 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/Storage.java
> +    FindResult find(String country, FindFilter filter) throws InputValidationException, StorageServerException;
RecordException will hide them

2021-11-09 12:40 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/http/impl/OAuthTokenClient.java
>          }
Yes, it is a piece of code from the constructor, that is used at a Storage initializing

2021-11-10 11:37 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/StorageImpl.java
> +     * @throws StorageCryptoException           if custom cipher validation fails
Yes. This piece of code is inside the constructor. Such exception could be thrown only during custom cipher validation there.

2021-11-17 13:46 UTC, RommeroInCountry approved these changes

2021-11-19 10:49 UTC, robert-par approved these changes

2021-11-22 14:05 UTC, merged