SDK-452
incountry/sdk-java pull request #254
Opened 2021-11-16 11:02 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-452](https://incountry.atlassian.net/browse/SDK-452)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-12-01 17:54 UTC, RommeroInCountry requested changes

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void dateComparingPositive1() throws InputValidationException {
datesWithOperatorsPositive

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void dateComparingPositive2() throws InputValidationException {
datesWithOperatorsPositive2

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void dateComparingPositive3() throws InputValidationException {
datesWithOperatorsPositive3

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void dateComparingPositive4() throws InputValidationException {
datesWithOperatorsPositive4

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void dateFilterValidationNegative1() {
dateFilterValidationNegativeOnNull

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void dateFilterValidationNegative2() {
dateFilterValidationNegativeOnKeyIsNullOnServerDate

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void dateFilterValidationNegative3() {
dateFilterValidationNegativeOnKeyIsNotNullOnServerDate

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void limitAndOffsetNegative1() {
limitAndOffsetNegativeOnZeroLimit

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void limitAndOffsetNegative2() {
limitAndOffsetNegativeOnLimitOver100

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void limitAndOffsetNegative3() {
limitAndOffsetNegativeOnNegativeOffset

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void sortNegative1() {
sortNegativeOnNullField

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void sortNegative2() {
sortNegativeOnNullOrder

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void sortNegative3() throws InputValidationException {
sortNegativeOnDuplicateField

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void searchKeysLikeNegative1() throws InputValidationException {
searchKeysLikeNegativeOnCombinationWithRegularSearchKey

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void searchKeysLikeNegative2() throws InputValidationException {
searchKeysLikeNegativeOnCombinationWithRegularSearchKey2

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void orConditionNegativeEmptyFilters1() {
orConditionNegativeOnNullArray

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void orConditionNegativeEmptyFilters2() {
orConditionNegativeOnEmptyArray

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void orConditionNegativeEmptyFilters3() {
Why this one throws?

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void orConditionNegativeEmptyFilter1() {
orConditionNegativeOnMultipleNullFilters

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void orConditionNegativeEmptyFilter2() throws InputValidationException {
orConditionNegativeOnNestedOrFilters

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/http/HttpExecutorImplTest.java
> +    void downloadFilePositive2() throws IOException, StorageException {
can't really tell the big difference with downloadFilePositive1

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/http/HttpExecutorImplTest.java
> +    void requestDifferentMethodsPositive() throws IOException, StorageException {
We have PATCH too somewhere in PoPAPI

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void migrateNegative1() throws StorageCryptoException, StorageConfigValidationException, SecretsProviderException, SecretsValidationException {
migrateNegativeWithZeroLimit

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void migrateNegative2() throws StorageCryptoException, StorageConfigValidationException, SecretsProviderException, SecretsValidationException {
migrateNegativeWithDisabledEncryption

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void writeResponseMisMatch() throws StorageException, IOException {
Mismatch. It's one word

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void findFilterParamsAnalyse(FindFilter filter, String notNullParam) throws StorageException {
findFilterCheckDataReceivedByServer

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void readPositiveNotFound1(RepetitionInfo repeatInfo) throws StorageException {
readPositiveNotFoundWith200Response

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void readPositiveNotFound2(RepetitionInfo repeatInfo) throws StorageException {
readPositiveNotFoundWith404Response

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void readPositiveNotFound1(RepetitionInfo repeatInfo) throws StorageException {
is this scenario viable for JavaSDK? Shouldn't it throw exception when trying to parse record?

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void initErrorOnInsufficientArgs(RepetitionInfo repeatInfo) {
getInstanceNegativeOn...

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void initPositive() throws StorageCryptoException, SecretsValidationException, SecretsProviderException, StorageConfigValidationException {
please for all tests below - init -> getInstance...

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void initNegativeIllegalPoolSize2() throws StorageConfigValidationException {
if possible i'd parametrize `initNegativeIllegalPoolSize1` + `initNegativeIllegalPoolSize2`
and `initNegativeIllegalPoolSize3` + `initNegativeIllegalPoolSize4`
and rename first two to `getInstanceNegativeOnIllegalPoolSize` and the latter two to `getInstanceNegativeOnIllegalConnectionsPerRoute`

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void initPositive() throws StorageCryptoException, SecretsValidationException, SecretsProviderException, StorageConfigValidationException {
please separate all constructor/init tests into separate file. This one is already too big to comprehend

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void findSearchKeysNegative1() throws InputValidationException {
findSearchKeysNegativeOnSearchKeysWithRegularKeys

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void findSearchKeysNegative2() throws InputValidationException {
findSearchKeysNegativeOnSearchKeysWithRegularKeys2

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void findSearchKeysNegative3() {
findSearchKeysNegativeOnSearchKeysTooShortInput

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void findSearchKeysNegative4() {
findSearchKeysNegativeOnSearchKeysTooLongInput

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void initNegativeNullConfig() {
please move this to another file as stated above. 

consider better test grouping/order for this file as this tests shouldn't be here anyways

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void retryDelayNegativeConfigValidation1() throws StorageClientException {
retryDelayNegativeOnInvalidBaseDelay

2021-12-01 17:54 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void retryDelayNegativeConfigValidation2() throws StorageClientException {
retryDelayNegativeOnMaxDelayLowerThanBaseDelay

2021-12-02 10:43 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/EncryptedDtoTransformerTest.java
> +    void getSecretsNegative3() throws StorageCryptoException {
There are different exception classes

2021-12-02 10:49 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/StorageConfigTest.java
> +    void getCustomEncryptionConfigsListPositive1() throws StorageCryptoException, InputValidationException {
setCryptoProviderPositiveWithCustomCipher

2021-12-02 10:51 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/StorageConfigTest.java
> +    void getCustomEncryptionConfigsListPositive2() {
getCryptoProviderPositiveDefaultConfiguration

2021-12-02 11:15 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/crypto/DefaultCipherTest.java
> +    void aesGcmPbkdf10kHexCipherNegative3() throws SecretsValidationException {
aesGcmPbkdf10kHexCipherNegativeNullCharset  - > aesGcmPbkdf10kHexCipherNegativeDecryptWithNullCharset
aesGcmPbkdf10kHexCipherNegative3 -> aesGcmPbkdf10kHexCipherNegativeEncryptWithNullCharset

2021-12-02 11:42 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/crypto/CustomCipherTest.java
> +        //one successful encryption
Yes. To get correct encrypted text

2021-12-02 12:11 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void orConditionNegativeEmptyFilters3() {
Because OR condition must have at least 2 filters, e.g.
a=1 AND 
b=2 AND
(c=3 OR d=4) AND
e=5

2021-12-02 12:11 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/search/FindFilterTest.java
> +    void orConditionNegativeEmptyFilters3() {
renamed to **orConditionNegativeSingleOrCondition**

2021-12-02 12:15 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/http/HttpExecutorImplTest.java
> +    void downloadFilePositive2() throws IOException, StorageException {
They are almost the same. The second will be deleted

2021-12-02 12:17 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/http/HttpExecutorImplTest.java
> +    void requestDifferentMethodsPositive() throws IOException, StorageException {
PATCH was added to test list

2021-12-02 12:52 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/StorageTest.java
> +    void readPositiveNotFound1(RepetitionInfo repeatInfo) throws StorageException {
fixed

2021-12-02 14:43 UTC, RommeroInCountry approved these changes

2021-12-03 14:52 UTC, robert-par approved these changes

2021-12-03 14:54 UTC, merged