SDK-484
incountry/sdk-java pull request #263
Opened 2021-12-09 16:16 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-484](https://incountry.atlassian.net/browse/SDK-484)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-12-09 17:37 UTC, RommeroInCountry requested changes

2021-12-09 17:37 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/HttpDaoImpl.java
> +            POP existedPop = result.get(transferPop.getId());
existingPop

2021-12-13 12:06 UTC, RommeroInCountry approved these changes

2021-12-13 15:07 UTC, robert-par approved these changes

2021-12-13 15:13 UTC, merged