SDK-192
incountry/sdk-java pull request #279
Opened 2022-02-03 09:15 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-192](https://incountry.atlassian.net/browse/SDK-192)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2022-04-21 17:23 UTC, RommeroInCountry requested changes

2022-04-21 17:23 UTC, RommeroInCountry commented on src/test/java/com/incountry/residence/sdk/http/PopExtractorTest.java
> +        assertTrue(endpoint2.isMidPop());
what about the case when we have both mini and mid? and mini is first in line? let's add that test case as well

2022-04-21 17:23 UTC, RommeroInCountry commented on src/main/java/com/incountry/residence/sdk/tools/dao/impl/PopExtractor.java
> +        boolean invalidTransferCountry = isNullOrEmpty(transferCountry.getId()) || !transferCountry.isActive() || transferCountry.getPop() == null || isNullOrEmpty(transferCountry.getOauth2Server());
isInvalid...

2022-04-21 17:23 UTC, RommeroInCountry commented on src/integration/java/com/incountry/residence/sdk/OAuthTest.java
> -    void tokenAccessorTest() throws StorageServerException, StorageCryptoException, StorageClientException {
this one is still a good and valid test. Let's keep it. We may simply try extracting the first oauth2 server from countries list for this test

2022-04-22 16:09 UTC, VladimirLevitskiy commented on src/main/java/com/incountry/residence/sdk/tools/http/HttpExecutor.java
> +    ApiResponse request(String url, String body, String audience, String oauth2Server, int retryCount,
it was from the infra JSON

2022-04-22 16:17 UTC, VladimirLevitskiy commented on src/test/java/com/incountry/residence/sdk/http/PopExtractorTest.java
> +        assertTrue(endpoint2.isMidPop());
it's already done at the test 'getCountryListPositiveCountryDuplication'

2022-04-27 11:55 UTC, robert-par approved these changes

2022-04-27 12:26 UTC, merged